name: CI & Deploy to Railway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations (sqlite)
        run: |
          python manage.py migrate --noinput || true

      - name: Run Django tests
        env:
          PYTHONUNBUFFERED: '1'
        run: |
          python manage.py test --verbosity=2

  deploy:
    name: Deploy to Railway
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node (for Railway CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Login to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          if [ -z "$RAILWAY_TOKEN" ]; then echo "Missing RAILWAY_TOKEN secret"; exit 1; fi
          railway login --token "$RAILWAY_TOKEN"

      - name: Link project (optional)
        env:
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          # If you want to explicitly link a Railway project by id, set the RAILWAY_PROJECT_ID secret.
          if [ -n "$RAILWAY_PROJECT_ID" ]; then
            railway link "$RAILWAY_PROJECT_ID" || true
          fi

      - name: Deploy (railway up)
        env:
          RAILWAY_ENV: ${{ secrets.RAILWAY_ENV }}
        run: |
          # Deploy the current branch to Railway. Set RAILWAY_ENV if you want a specific environment (eg. production).
          if [ -n "$RAILWAY_ENV" ]; then
            railway up --ci --detach --environment "$RAILWAY_ENV"
          else
            railway up --ci --detach
          fi

      - name: Post-deploy message
        run: echo "Deployment attempt finished. Check Railway dashboard for status."
